language: elixir
elixir:
  - 1.9
otp_release:
  - 22.0
sudo: false

matrix:
  include:
    - env: PHOENIX_VERSION=1.2.6
    - env: PHOENIX_VERSION=1.3.4
    - env: PHOENIX_VERSION=1.4.5
    - env: PHOENIX_VERSION=1.5.3
    - env: PHOENIX_VERSION=1.6.6
    - env: PHOENIX_VERSION=1.7.4
    - env: PHOENIX_VERSION=1.8.2
    - env: PHOENIX_VERSION=1.9.4
    - env: PHOENIX_VERSION=1.10.2

before_script:
  - MIX_ENV=ci PHOENIX_VERSION=$PHOENIX_VERSION mix deps.get

script:
  - mix test.lint
  - mix test
